# These are supported funding model platforms

#github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: BioblazePayne
#open_collective: # Replace with a single Open Collective username
#ko_fi: # Replace with a single Ko-fi username
tidelift: npm/discord.js-router
custom: https://www.paypal.me/BioblazePayne
